<?php

namespace AppliFraisBundle\Repository;

/**
 * Fiche_FraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Fiche_FraisRepository extends \Doctrine\ORM\EntityRepository
{
}
