<?php

namespace AppliFraisBundle\Repository;

/**
 * Frais_Hors_ForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Frais_Hors_ForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
