<?php

namespace AppliFraisBundle\Repository;

/**
 * Liste_FraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Liste_FraisRepository extends \Doctrine\ORM\EntityRepository
{
}
